//go:build !ignore_autogenerated

// Manually written for bootstrap — replace with `make generate` once controller-gen is installed.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	runtime "k8s.io/apimachinery/pkg/runtime"
)

// McuNode

func (in *McuNode) DeepCopyInto(out *McuNode) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	out.Spec = in.Spec
	in.Status.DeepCopyInto(&out.Status)
}

func (in *McuNode) DeepCopy() *McuNode {
	if in == nil {
		return nil
	}
	out := new(McuNode)
	in.DeepCopyInto(out)
	return out
}

func (in *McuNode) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *McuNodeList) DeepCopyInto(out *McuNodeList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]McuNode, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *McuNodeList) DeepCopy() *McuNodeList {
	if in == nil {
		return nil
	}
	out := new(McuNodeList)
	in.DeepCopyInto(out)
	return out
}

func (in *McuNodeList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *McuNodeSpec) DeepCopyInto(out *McuNodeSpec) { *out = *in }

func (in *McuNodeStatus) DeepCopyInto(out *McuNodeStatus) {
	*out = *in
	if in.LastHeartbeat != nil {
		t := *in.LastHeartbeat
		out.LastHeartbeat = &t
	}
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

// McuDeployment

func (in *McuDeployment) DeepCopyInto(out *McuDeployment) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ObjectMeta.DeepCopyInto(&out.ObjectMeta)
	in.Spec.DeepCopyInto(&out.Spec)
	in.Status.DeepCopyInto(&out.Status)
}

func (in *McuDeployment) DeepCopy() *McuDeployment {
	if in == nil {
		return nil
	}
	out := new(McuDeployment)
	in.DeepCopyInto(out)
	return out
}

func (in *McuDeployment) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *McuDeploymentList) DeepCopyInto(out *McuDeploymentList) {
	*out = *in
	out.TypeMeta = in.TypeMeta
	in.ListMeta.DeepCopyInto(&out.ListMeta)
	if in.Items != nil {
		in, out := &in.Items, &out.Items
		*out = make([]McuDeployment, len(*in))
		for i := range *in {
			(*in)[i].DeepCopyInto(&(*out)[i])
		}
	}
}

func (in *McuDeploymentList) DeepCopy() *McuDeploymentList {
	if in == nil {
		return nil
	}
	out := new(McuDeploymentList)
	in.DeepCopyInto(out)
	return out
}

func (in *McuDeploymentList) DeepCopyObject() runtime.Object {
	if c := in.DeepCopy(); c != nil {
		return c
	}
	return nil
}

func (in *McuDeploymentSpec) DeepCopyInto(out *McuDeploymentSpec) {
	*out = *in
	out.Firmware = in.Firmware
	if in.NodeSelector != nil {
		in, out := &in.NodeSelector, &out.NodeSelector
		*out = make(map[string]string, len(*in))
		for k, v := range *in {
			(*out)[k] = v
		}
	}
}

func (in *McuDeploymentStatus) DeepCopyInto(out *McuDeploymentStatus) {
	*out = *in
	if in.Conditions != nil {
		in, out := &in.Conditions, &out.Conditions
		*out = make([]metav1.Condition, len(*in))
		copy(*out, *in)
	}
}

func (in *FirmwareSpec) DeepCopyInto(out *FirmwareSpec) { *out = *in }
